using FSW.Controls.Html;
using FSW.Core;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FSW.Diagnostic.UnitTests
{
    public class EmptyPageResult: IDisposable
    {
        public int UnitTestRequestId;
        public Pages.AutoGeneratedPage Page;
        public Controls.DiagnosticManager DiagnosticManager => Page.DiagnosticManager;
        public FSWPage.PageLock ServerSideLock => Page.ServerSideLock;
        public Div Container => Page.Container;
        public TaskCompletionSource<EmptyPageResult> TaskCompletionSource;

        public Task KeepAlive(TimeSpan delay)
        {
            return Task.Delay(delay);
        }

        public void Dispose()
        {
            using (Page.ServerSideLock)
                Page.DiagnosticManager.CloseTab();
            System.Threading.Thread.Sleep(TimeSpan.FromMilliseconds(10));
        }
    }
}
