using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FSW.Controls.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FSW.Diagnostic.Pages
{
    public class AutoGeneratedPage : Core.FSWPage
    {
        public Controls.DiagnosticManager DiagnosticManager = new Controls.DiagnosticManager();

        public Div Container = new Div();

        public override void OnPageLoad()
        {
            base.OnPageLoad();

            UnitTestsManager.ProcessPendingUnitTestRequest(int.Parse(UrlManager.Parameters["requestId"]), this);
        }
    }
}